#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""generate-journal-index.py — the vendored regenerator for
`<docs_dir>/journal/index.md`.

`<docs_dir>/journal/index.md` is a *derived* artifact — the tree schema and its
template twin both mark the row "REGENERATED by `generate-journal-index.py`.
One row per month file; never hand-edited." — and this script is
`rule:regenerator-plus-drift-gate`'s[^regen-gate] answer for it: one row per
`<docs_dir>/journal/YYYY-MM.md` file, newest month first, each cell computed by
`crux/scripts/journal_index.py`'s `derive_row`/`render_index` from the entries
that month file holds and never from the row it replaces
(`rule:journal-index-row-is-derived-on-every-write`[^derived-row]).

FAIL-CLOSED BEHAVIOUR. A month file this script cannot describe — a name
outside the `YYYY-MM.md` grammar, a symlink, a non-regular file, a file
ending inside a fence its own text never closes, or a file carrying an entry
heading whose category is outside the journal enum — refuses the whole run in
ALL THREE modes, write and `--dry-run` and `--check-stdin`: exit 1, a
non-empty `validation_errors` list of `{"file", "error"}` on stdout, and
nothing written. The category refusal is the narrow one: a heading is
reported only when it would open an entry but for that token, so a fenced
example and a forged date each stay with the lane that already owns them.

Exit 2 stays reserved for a genuine environment failure (a malformed
`.bionic.yml`, an unresolvable repo root, a containment refusal on a
directory a checkout controls) — never for a hand-edited journal file, which
is a document defect a human repairs.

AN ABSENT JOURNAL SURFACE IS NOT A REFUSAL. A tree with no
`<docs_dir>/journal/` directory at all carries no derived artifact, so there
is nothing that can have drifted. Write mode and `--dry-run` each exit 0 and
set `"surface_absent": true` on the JSON — a positive discriminator, not a
silent pass, matching `generate-reviews-index.py`'s precedent. `--check-stdin`
takes no such short circuit: it still has stdin content to validate, so it
falls through to an empty walk (see the comment on that branch below).

`--check-stdin --month YYYY-MM` is the preflight channel `log-work` uses
before it writes a new journal entry (decision (v) of the cycle that added
this script): it substitutes the given bytes for the named month's file in
the same directory walk `--dry-run` performs, validates the whole resulting
corpus and the output index path (guard 7), and writes nothing under any
input. It reports admissibility only —
`{"check": "ok", "month": "<YYYY-MM>", "entries": N}` at exit 0, or a
`validation_errors` list at exit 1 — and never a drift verdict, because a
stale row before a write is the normal state rather than a finding.
`--check-stdin` and `--dry-run` are mutually exclusive at the argument-parser
level.

SECURITY GUARDS, IN THE ORDER THEY RUN (each named so a reviewer can check
this list against the code rather than trust the prose):

  1. `--repo-root` is resolved with `Path(...).resolve()` before anything
     else.
  2. `docs_dir` containment under the repo root is the job of
     `bionic_config.load_config` and is not re-implemented here.
  3. `<tree>/journal` is checked contained under the tree by `_contained`
     first, then refused outright if it is a symlink at all. Both refusals
     raise `OSError` into the environment lane (exit 2). Containment runs
     BEFORE the symlink refusal, so a `journal` symlink resolving OUTSIDE the
     tree fails containment rather than reporting `surface_absent`; the
     symlink refusal then catches every remaining case, including a `journal`
     symlink that resolves INSIDE the tree. A symlinked `journal` directory
     is refused, full stop — this script admits only a real directory at
     that name.
  4. Every directory entry is refused if `entry.is_symlink()` is true,
     BEFORE the `is_file()` test and BEFORE the dotfile skip — `is_file()`
     follows a symlink, and a leading dot must not be a way past this guard.
  5. Every remaining candidate is refused if it is not a regular file.
  6. Every admitted name is matched against the closed month-file grammar
     `^[0-9]{4}-(0[1-9]|1[0-2])\\.md\\Z` under `re.fullmatch` — `[0-9]`,
     never `\\d`, and `\\Z`, never `$`, for the same reasons
     `journal_index.MONTH_RE` states. `index.md` is skipped (it is the
     output); a non-symlink dotfile is skipped, which is how guard 8's
     temporary file `.index.md.tmp` stays out of this grammar's reach; every
     other refused name is refused with a `validation_errors` entry, never
     silently dropped.
  7. The OUTPUT path (`<tree>/journal/index.md`) is validated BEFORE it is
     read, in ALL THREE modes: contained under the tree, refused if a
     symlink, refused if it exists and is not a regular file. A non-existent
     index is permitted — it reads as empty and gets written. The guard sits
     ABOVE the check-mode return, so `--check-stdin` runs it too: the index
     is invisible to the walk (`index.md` is skipped as the output), and a
     preflight that stopped short of this guard would admit a write that
     write mode then refuses. The guard writes nothing, so running it in
     check mode costs nothing. This guard has NO counterpart in
     `generate-reviews-index.py`, which reads its own index with a bare
     `is_file()` test and no prior symlink or containment check (see that
     script's line ~417) — that gap is a recorded follow-on, not fixed here
     and not inherited here.
  8. The write goes through `_atomic_write_text`, WRITE MODE ONLY —
     `--dry-run` and `--check-stdin` both stop before this guard. Its
     temporary file is `.index.md.tmp`, dot-prefixed so that a run killed
     between the `os.open` and the `os.replace` leaves behind debris guard 6
     skips rather than a name guard 6 refuses.
  9. Every filename and error string quoted back into `validation_errors` or
     onto stderr is routed through `untrusted.redact` at `MESSAGE_LIMIT`.

WHY GUARD 3 EXITS 2 WHILE GUARDS 4 AND 7 EXIT 1. All three can be tripped by
a symlink, and the lanes differ on purpose. Guards 1, 2 and 3 resolve the
tree's LAYOUT — where the repo root is, where `docs_dir` is, where `journal`
is. They answer "which directory am I about to read", they raise into one
`except (BionicConfigError, OSError)` block, and no edit to any document
repairs them. A `journal` resolving outside the checkout is a statement about
the checkout, and so is a `journal` that is a symlink at all — guard 3 now
carries two refusals, containment and the symlink refusal, and both are
LAYOUT findings with nothing for a document edit to repair. That is the
environment lane: exit 2, a message on stderr, no JSON. Guards 4 to 7 inspect
the FILES inside an already-resolved surface — the month files and the
index. Those are contents a checkout's author put there, each refusal names
one file, and each is repaired by removing or rewriting that file. That is
the document lane: exit 1, one `validation_errors` entry per file. The
dividing line is layout versus contents, not the mechanism: guard 3's two
refusals both apply to the `journal` directory ITSELF, while guards 4 and 7
test `is_symlink()` on the FILES a directory contains. Two consequences make
the line worth keeping. Exit 1 promises a `{"file", "error"}` pair naming a
document, and guard 3's subject is a directory with no such file to name.
And `log-work` reports an exit-2 refusal as an environment failure, which is
the sentence a reader of "your `journal` is a symlink" needs, whether that
symlink points inside or outside the checkout.

Month files are opened with `os.open(path, os.O_RDONLY | os.O_NOFOLLOW)`,
never a bare `read_text` after an `is_symlink()` test — the same discipline
the write path already uses.

EVERY REPORTED PATH IS THE LITERAL `<docs_dir>/journal` PATH. Because guard 3
refuses any symlinked `journal` outright, the only layout this script ever
admits is a real directory at that literal name — so the reported prefix on
`path`, `written` and `validation_errors.file` is always `<docs_dir>/journal`
itself. No checkout-controlled directory basename ever reaches those keys,
so they need no redaction and cannot disagree with the redacted
`validation_errors.file` key beside them (guard 9). Refusing the symlink also
closes a second gap containment alone left open: a `journal` symlinked to a
SIBLING concern directory — `journal -> adrs`, say — resolves under the tree
and would have passed containment, letting write mode overwrite that
sibling's own `index.md`. Refusing the symlink stops that clobber before any
file is read or written, not just the reporting surface that would have
named it.

Usage:
  generate-journal-index.py [--repo-root DIR]                 rewrite journal/index.md
  generate-journal-index.py --dry-run [--repo-root DIR]       exit 1 + JSON if drift
  generate-journal-index.py --check-stdin --month YYYY-MM     preflight one month's
      [--repo-root DIR] < prospective-month-file.md            prospective content

Exit: 0 clean/written/checked-ok/surface-absent · 1 drift or a document
defect (JSON on stdout) · 2 environment/capability failure (stderr).

[^regen-gate]: rule:regenerator-plus-drift-gate
[^derived-row]: rule:journal-index-row-is-derived-on-every-write
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from bionic_config import BionicConfigError, load_config  # noqa: E402
from journal_index import (  # noqa: E402
    MONTH_RE,
    derive_row,
    find_unclosed_fence,
    render_index,
    unknown_category_headings,
)
from untrusted import MESSAGE_LIMIT, redact  # noqa: E402

# The filename grammar (guard 6). Built from the same digit-class and anchor
# discipline as `journal_index.MONTH_RE` — `[0-9]`, never `\d`; `\Z` under
# `fullmatch`, never `$` under `match` — applied to the `.md`-suffixed name
# rather than the bare month string.
MONTH_FILE_RE = re.compile(r"^[0-9]{4}-(0[1-9]|1[0-2])\.md\Z")


def _contained(child: Path, parent: Path, subject: str) -> Path:
    """`child`, refused when it resolves outside `parent`.

    [SECURITY:S5] Raised as `OSError` so a symlinked directory lands in the
    environment lane (exit 2) rather than being read as a document defect —
    `_contained` never returns a value the fact-of-a-symlink helped produce.
    """
    resolved = child.resolve()
    parent_resolved = parent.resolve()
    if resolved != parent_resolved and parent_resolved not in resolved.parents:
        raise OSError(
            f"refusing to read {child}: the {subject} resolves to {resolved}, "
            f"which is not contained under {parent_resolved}")
    return child


def _atomic_write_text(path: Path, body: str, *, contained_under: Path) -> None:
    """Atomic UTF-8 text write with no platform newline translation.

    Vendored from `generate-reviews-index.py`'s implementation rather than
    imported — that script is itself hyphen-named and not importable, and
    every regenerator in this tree carries its own copy of this guard
    (`compile-doctrine.py` / `summarize-adrs.py` / `signoff-backfill.py` /
    `generate-reviews-index.py`), same guards, same order, same exception
    type. Change one, change all.

    ONE DELIBERATE DIVERGENCE from those siblings: the temporary file is
    `.index.md.tmp`, not `index.md.tmp`. Guard 6 walks the directory the
    temporary file lives in under a closed filename grammar, so an undotted
    `index.md.tmp` left behind by a killed run is refused BY NAME in all
    three modes and bricks every later run until a human deletes a file they
    have no reason to look for. The dot prefix puts it under the walk's
    existing dotfile skip, which runs AFTER the symlink refusal, so a
    symlinked `.index.md.tmp` is still refused. The `FileExistsError`
    refusal below is reachable only because of this. The siblings walk no
    such directory and keep the undotted name.
    """
    root_resolved = Path(contained_under).resolve()
    parent_resolved = path.parent.resolve()
    if parent_resolved != root_resolved \
            and root_resolved not in parent_resolved.parents:
        raise OSError(
            f"refusing to write {path}: the parent directory resolves to "
            f"{parent_resolved}, which is not contained under the validated "
            f"tree dir {root_resolved} — a symlinked intermediate directory "
            "would put journal index content outside the tree"
        )
    tmp = path.with_name("." + path.name + ".tmp")
    for label, candidate in (("target", path), ("temporary file", tmp)):
        if candidate.is_symlink():
            raise OSError(
                f"refusing to write {path}: the {label} {candidate} is a symlink — "
                "writing through it would put journal index content in the "
                "link's target"
            )
    try:
        fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, 0o644)
    except FileExistsError as exc:
        raise OSError(
            f"refusing to write {path}: the temporary file {tmp} already exists; "
            "remove it after checking what created it"
        ) from exc
    except OSError as exc:  # ELOOP from O_NOFOLLOW, or an unwritable directory
        raise OSError(f"refusing to write {path}: cannot create {tmp} ({exc})") from exc
    try:
        with os.fdopen(fd, "wb") as handle:
            handle.write(body.encode("utf-8"))
        os.replace(tmp, path)
    except Exception:
        try:
            tmp.unlink()
        except FileNotFoundError:
            pass
        raise


def _read_regular_file(path: Path) -> str:
    """`path`'s UTF-8 text, opened `O_RDONLY | O_NOFOLLOW`.

    Raises `OSError` (a symlink slipping past an earlier check, ELOOP, a
    permission failure) or `UnicodeDecodeError` — both are caught by the
    caller and reported as a `validation_errors` entry.
    """
    fd = os.open(path, os.O_RDONLY | os.O_NOFOLLOW)
    with os.fdopen(fd, "rb") as handle:
        raw = handle.read()
    return raw.decode("utf-8")


def _validate_output_index(index_path: Path, tree: Path, rel: str) -> str:
    """Guard 7: the output path, validated and read BEFORE any use.

    Containment, then refuse a symlink, then refuse an existing non-regular
    file. A non-existent index is the permitted case: it reads as empty and
    `main` writes it. Raises `OSError` on any refusal, converted by the
    caller into a `validation_errors` entry — this is a document-shaped
    refusal (the index a checkout produced), not an environment failure.

    Both refusals name `rel`, the tree-relative path, so the `error` string
    agrees with the `file` key beside it and no absolute checkout path leaks
    onto stdout. The containment refusal is the one exception: `_contained`
    names both resolved paths, because where the path escaped TO is the whole
    finding.
    """
    _contained(index_path, tree, "journal index")
    if index_path.is_symlink():
        raise OSError(f"{rel} is a symlink — refusing to read or write through it")
    if index_path.exists() and not index_path.is_file():
        raise OSError(f"{rel} exists and is not a regular file")
    if not index_path.exists():
        return ""
    return _read_regular_file(index_path)


def _walk_journal_dir(journal_dir: Path, rel_journal: str) -> tuple[dict[str, tuple[str, str]], list[dict]]:
    """`({month: (text, rel path)}, validation_errors)` for `journal_dir`.

    Guards 4-6, in order, over every directory entry. A file this function
    could not read (I/O error, bad encoding) is reported the same way a
    grammar refusal is — a `validation_errors` entry naming the file.
    """
    month_texts: dict[str, tuple[str, str]] = {}
    errors: list[dict] = []
    try:
        entries = sorted(journal_dir.iterdir(), key=lambda p: p.name)
    except OSError as exc:
        raise OSError(f"could not list {journal_dir}: {exc}") from exc

    for entry in entries:
        name = entry.name
        rel = str(Path(rel_journal) / name)
        # Guard 4: symlink refusal, BEFORE is_file() and BEFORE the dotfile
        # skip — is_file() follows a symlink.
        if entry.is_symlink():
            errors.append({"file": rel, "error": "is a symlink — the journal "
                           "grammar admits only regular files, and following "
                           "one would read outside the tree"})
            continue
        if name == "index.md":
            continue  # the output, not an input
        if name.startswith("."):
            continue  # editor/filesystem debris, never a month file
        # Guard 5: regular file only.
        if not entry.is_file():
            errors.append({"file": rel, "error": "is not a regular file"})
            continue
        # Guard 6: the closed month-file grammar.
        if not MONTH_FILE_RE.fullmatch(name):
            errors.append({"file": rel, "error": "name is outside the "
                           "journal grammar — expected index.md or a "
                           "YYYY-MM.md month file"})
            continue
        month = name[:-len(".md")]
        try:
            text = _read_regular_file(entry)
        except UnicodeDecodeError as exc:
            errors.append({"file": rel, "error": f"is not valid UTF-8 ({exc})"})
            continue
        except OSError as exc:
            errors.append({"file": rel, "error": f"could not be read ({exc})"})
            continue
        month_texts[month] = (text, rel)
    return month_texts, errors


def _rel_index(rel_journal: str) -> str:
    return str(Path(rel_journal) / "index.md")


def _redact_errors(errors: list[dict]) -> list[dict]:
    # [SECURITY:S1] Guard 9: every filename and error string quoted back into
    # `validation_errors` or onto stderr is routed through `untrusted.redact`
    # at `MESSAGE_LIMIT`, not the tighter per-value default — a composed
    # refusal (a containment message quoting a full resolved path) is this
    # project's own prose plus one path, not raw untrusted file content, and
    # the tighter default would cut a real two-sentence refusal in half.
    return [{"file": redact(e["file"], quoted=False, limit=MESSAGE_LIMIT),
             "error": redact(e["error"], quoted=False, limit=MESSAGE_LIMIT)} for e in errors]


def _emit_validation_errors(errors: list[dict], rel_index: str | None) -> int:
    payload: dict = {"validation_errors": _redact_errors(errors)}
    if rel_index is not None:
        payload["path"] = rel_index
    print(json.dumps(payload, sort_keys=True))
    sys.stderr.write(
        "generate-journal-index: "
        + "; ".join(f"{e['file']}: {e['error']}" for e in payload["validation_errors"])
        + "\n")
    return 1


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description="Regenerate <docs_dir>/journal/index.md from the monthly journal files.")
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument("--dry-run", action="store_true")
    mode.add_argument("--check-stdin", action="store_true",
                      help="Validate prospective stdin content for --month without writing.")
    ap.add_argument("--repo-root", default=".")
    ap.add_argument("--month", default=None,
                    help="The YYYY-MM month --check-stdin's stdin content belongs to.")
    args = ap.parse_args(argv)

    if args.check_stdin and args.month is None:
        sys.stderr.write("generate-journal-index: --check-stdin requires --month YYYY-MM\n")
        return 2
    if args.month is not None and not args.check_stdin:
        sys.stderr.write("generate-journal-index: --month is only valid with --check-stdin\n")
        return 2
    if args.month is not None and not MONTH_RE.fullmatch(args.month):
        return _emit_validation_errors(
            [{"file": "--month", "error": f"{args.month!r} is not a valid YYYY-MM month"}],
            None)

    # Guards 1-3, INSIDE the try: `Path.resolve()`, `load_config`, and the
    # journal-directory containment check all raise on a checkout-controlled
    # failure — a symlinked tree dir, a malformed .bionic.yml, a `journal`
    # symlink escaping the tree. All three land in the environment lane.
    try:
        root = Path(args.repo_root).resolve()
        config = load_config(root, require_tree=True)
        tree = config.docs_root
        journal_dir = tree / "journal"
        _contained(journal_dir, tree, "journal directory")
        if journal_dir.is_symlink():
            raise OSError(
                f"refusing to use {config.docs_dir}/journal: it is a "
                "symlink, but the journal concern must be a real directory "
                "— replace the link with a directory, or point docs_dir at "
                "the tree that actually holds it")
    except (BionicConfigError, OSError) as exc:
        sys.stderr.write(
            f"generate-journal-index: {redact(exc, quoted=False, limit=MESSAGE_LIMIT)}\n")
        return 2

    rel_journal = str(Path(config.docs_dir) / "journal")
    rel_index = _rel_index(rel_journal)

    # Surface-absent: checked AFTER both halves of guard 3, so no symlinked
    # `journal` reaches it. One resolving outside the tree fails containment
    # and one resolving inside fails the symlink refusal — both exit 2 rather
    # than reporting surface_absent (exit 0). A genuinely absent directory is the
    # only input that reaches this lane — and, for `--dry-run`/write mode,
    # the only one that short-circuits: check mode still has stdin content to
    # validate even when no journal directory exists yet (the first entry a
    # brand-new tree ever journals), so it falls through to the walk below
    # over an empty `month_texts` rather than reporting a stale `entries: 0`.
    if not journal_dir.is_dir():
        if not args.check_stdin:
            payload = {"path": rel_index, "surface_absent": True}
            payload |= {"drift": False} if args.dry_run else {"written": None}
            print(json.dumps(payload, sort_keys=True))
            return 0
        month_texts, errors = {}, []
    else:
        try:
            month_texts, errors = _walk_journal_dir(journal_dir, rel_journal)
        except OSError as exc:
            sys.stderr.write(
                f"generate-journal-index: {redact(exc, quoted=False, limit=MESSAGE_LIMIT)}\n")
            return 2

    stdin_decode_error: dict | None = None
    if args.check_stdin:
        raw = sys.stdin.buffer.read()
        try:
            stdin_text = raw.decode("utf-8")
        except UnicodeDecodeError as exc:
            stdin_decode_error = {
                "file": str(Path(rel_journal) / f"{args.month}.md"),
                "error": f"stdin is not valid UTF-8 ({exc})",
            }
        else:
            rel = str(Path(rel_journal) / f"{args.month}.md")
            month_texts[args.month] = (stdin_text, rel)

    if stdin_decode_error is not None:
        errors.append(stdin_decode_error)

    # Refuse-and-preserve: a month file ending inside an open fence is a
    # document defect, named with the 1-based line number of the unclosed
    # opener. Every input is validated before the output is touched, so one
    # bad month file cannot leave a half-written index.
    rows = []
    for month in sorted(month_texts, reverse=True):
        text, rel = month_texts[month]
        unclosed = find_unclosed_fence(text)
        if unclosed is not None:
            errors.append({"file": rel, "error": f"line {unclosed} opens a "
                           "fence never closed — entry boundaries below it "
                           "are ambiguous"})
            continue
        # A heading that would open an entry but for its category token. Read
        # as body prose it costs the month an entry with every gate still
        # green, which is how the journal index undercounted 2026-09 for a
        # release cycle. Reported per heading, in line order, so a file with
        # several near misses is repaired in one pass.
        near_misses = unknown_category_headings(text)
        if near_misses:
            for lineno, category in near_misses:
                errors.append({"file": rel, "error": (
                    f"line {lineno} is an entry heading whose category "
                    f"{category!r} is outside the journal category enum — "
                    "correct the heading, or add the category to the tree "
                    "schema and to CATEGORIES in journal_index.py")})
            continue
        rows.append(derive_row(month, text))

    if errors:
        return _emit_validation_errors(errors, rel_index)

    # Guard 7, ABOVE the check-mode return so it runs in all three modes. An
    # `index.md` that is a directory or a FIFO is skipped by the walk (it is
    # the output), so this is the only place any mode sees it — returning
    # before it made `--check-stdin` admit a write that write mode refused.
    # The guard writes nothing. `UnicodeDecodeError` is caught beside
    # `OSError` because the read below can raise it on a non-UTF-8 index, and
    # a traceback would break the exit-1 contract of valid JSON on stdout.
    index_path = tree / "journal" / "index.md"
    try:
        have = _validate_output_index(index_path, tree, rel_index)
    except (OSError, UnicodeDecodeError) as exc:
        return _emit_validation_errors(
            [{"file": rel_index, "error": str(exc)}], rel_index)

    if args.check_stdin:
        entries = next((r["entries"] for r in rows if r["month"] == args.month), 0)
        print(json.dumps({"check": "ok", "month": args.month, "entries": entries},
                         sort_keys=True))
        return 0

    dated = [r["last"] for r in rows if r["last"] != "—"]
    last_updated = max(dated) if dated else "—"
    want = render_index(rows, last_updated)

    if args.dry_run:
        drift = have != want
        print(json.dumps({"drift": drift, "path": rel_index}, sort_keys=True))
        return 1 if drift else 0

    try:
        _atomic_write_text(index_path, want, contained_under=tree)
    except OSError as exc:
        sys.stderr.write(
            f"generate-journal-index: {redact(exc, quoted=False, limit=MESSAGE_LIMIT)}\n")
        return 2
    print(json.dumps({"written": rel_index}, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
